### PR TITLE
Admin workspace

### LINKED ISSUE #5: [ADMIN] Create admin service
We need admin panel to manage workspace

### PR DESCRIPTION
**Pull request by XiaoXuxxxx**
### What
Briefly describe this feature / fix / refactor

#### Workspace
create workspace route: 3a1076b cd646f7 4338c02 623d401 f30249f

#### Assignment
create assignment: 2087bf9 c1e605f d0ba65d 6644e1c

#### Testcase
create testcases: 24a778f

#### Participant
create participant route: 3a7fe57 a6d6b00 d74e2c0
workspace role middleware: cabadac 5baa4ee

#### Submission
get submissions based on workspace role (if role is more than `OWNER` then get all submissions, if the role is `MEMBER` then get only member's submission):  330d554

#### User
***This is not about the admin workspace***
change user info: 8add514 d5fffb1 be12a47 574b150

### Why
Describe the reason why we need this feature / fix / refactor
because of this #5 

### How
Describe the feature / fix / refactor in detail.

- Explain the technical solution you have done to create / fix this pull request
- Attach the screenshot (if applicable)

### Todo list (if applicable)
- [x] Open my computer

## Checklist
- [x] Drink juicy beverage when coding ☕️
- [x] Explained the purpose of this PR
- [x] Tested on **Local machine** and verified that there're no visible errors
- [x] Tested on **Staging server** and verified that there're no visible errors
- [ ] Updated documentation (if applicable)
- [ ] Added or updated test suite for the changes (if applicable)

### CODE REVIEW

**Comment by XiaoXuxxxx** [comment]
GLHF for review 500 lines of code na kub, eiei

**Comment by riflowth** [comment]
Link #5

**Comment by riflowth** [comment]
@XiaoXuxxxx Thank you for hard-working 💪 
I'm going to refactor some codes for consistency. I think we need to write out the coding standard LOL.

**Comment by riflowth** [comment]
We need to reimplement this feature due to our new coding standard

**Pull request closed without merging**
